apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.policy.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.policy.appLabels.main_backend }}
          ports:
            - port: {{ .Values.policy.ports.main_port }}
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.policy.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.policy.appLabels.report_backend }}
          ports:
            - port: {{ .Values.policy.ports.report_port }}
    egress:
        - to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.policy.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.policy.appLabels.main_backend }}
          ports:
            - port: {{ .Values.policy.ports.main_port }}
        - to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.policy.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.policy.appLabels.report_backend }}
          ports:
            - port: {{ .Values.policy.ports.report_port }}