apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.egress.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.egress.appLabel }}
          ports:
            - port: {{ .Values.service.port }}
    egress:
        - to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: {{ .Values.egress.namespace }}
              podSelector:
                matchLabels:
                    app: {{ .Values.egress.appLabel }}
          ports:
            - port: {{ .Values.egress.port }}