apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.secret.password }}
  username: {{ .Values.secret.username }}
