replicaCount: 1

image:
  repository: aswinvj/pomodoro-microservices
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7070
  nodeport: 30170

configmap:
  mountpath: /app/config.js
  subpath: config.js

secretName: backend-secrets

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi