replicaCount: 1

image:
  repository: techiescamp/pomodoro-backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7000
  nodeport: 30163

configmap:
  mountpath: /app/config.js
  subpath: config.js

secretName: backend-secrets

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

## Configmap template file data
port: 7000
mongourl: mongodb://adminuser:password123@pomodoro-db.db.svc.cluster.local:27017/pomodoro?authSource=admin
jwt_key: mysecret
session_secret: supersecret
frontend_url: http://localhost:3000
report_backend_url: http://localhost:7070
jaeger_trace_url: http://simplest-collector.observability.svc.cluster.local:14268

## Network Policy
ingress:
  namespace: frontend
  appLabel: frontend
  port: 3000

egress:
  namespace: db
  appLabel: db
  port: 27017
