replicaCount: 1

image:
  repository: techiescamp/pomodoro
  tag: "7.0.0"
  pullPolicy: IfNotPresent

configmap:
  mountpath: /app/src/config.js
  subpath: config.js

service:
  type: NodePort
  port: 3000
  nodeport: 32749

backend_url: http://34.71.163.101:30163
reports_url: http://34.71.163.101:30170
metrics_url: http://34.71.163.101:30163/metrics
jaeger_trace_url: http://52.43.65.153:30894

## Network Policy

egress:
  namespace: backend
  appLabel: backend
  port: 7000

autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
