apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    const config = {
      server: {
        port: "{{ .Values.port }}"
      },
      database: {
        mongoUrl: "{{ .Values.mongourl }}"
      },
      observability: {
        jaeger_trace_url: "{{ .Values.jaeger_trace_url }}"
      }
    }

    module.exports = config;