apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
      matchLabels:
        app: backend
        app: report-backend
      
  policyTypes:
  - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.frontend.namespace }}
          podSelector:
            matchLabels:
              app: {{ .Values.frontend.appLabel }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.db.namespace }}
          podSelector:
            matchLabels:
              app: {{ .Values.db.appLabel }}