apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.egress.namespace }}
          podSelector:
            matchLabels:
              app: {{ .Values.egress.appLabels.main_backend }}
      ports:
        - port: {{ .Values.egress.ports.main_port }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.egress.namespace }}
          podSelector:
            matchLabels:
              app: {{ .Values.egress.appLabels.report_backend }}
      ports:
        - port: {{ .Values.egress.ports.report_port }}