replicaCount: 1
image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

pvc:
  storage: 1Gi
secret:
  password: cGFzc3dvcmQxMjM=
  username: YWRtaW51c2Vy
service:
  type: ClusterIP
  port: 27017
  nodePort: 32701

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

## Network Policy

egress:
  namespace: backend
  appLabel: backend
  port: 7000

